name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Triggers workflow on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name larrycapstoneacr3

    - name: Build and Tag Docker Image
      run: |
        docker build -t larrycapstoneacr3.azurecr.io/wavy-tsunami-app:latest .

    - name: Push Docker Image to ACR
      run: |
        docker push larrycapstoneacr3.azurecr.io/wavy-tsunami-app:latest
